# Generated by Django 4.1.6 on 2023-02-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Csd_id',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='')),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='webpages.rank')),
            ],
        ),
    ]
