# Generated by Django 4.1.6 on 2023-02-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_alter_csd_id_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csd_id',
            name='id',
        ),
        migrations.AddField(
            model_name='csd_id',
            name='serial',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
